### ISSUE TITLE
Fix for password recovery failure due to invalid message ID and other issues

### ISSUE THREAD

**Issue by johnheenan** [virtualmin/virtualmin-password-recovery#4]
As reported in https://forum.virtualmin.com/t/password-recovery-still-fails/120625, there are multiple issues with the virtualmin password recovery module. 

All known issues, except one, can be fixed by removing trailing new lines in the $emailto variable in file `email.cgi`. After the `my $emailto` to lines the following cleans trailing new lines:
```
$emailto=~ s/\n+$//;
```
I will this solution up a PR. At the very least it is immediately obvious it causes no harm.

Clearly a better solution is to provide a fix so no email addresses are stored (and so recovered) with trailing new lines.

The remaining issue is that the orange "Forgot your Usermin password?" box is not removed from Usermin logon box when the module is uninstalled. This can of course be easily fixed in file `uninstall.pl` by adding missing corresponding code as for removal for orange box of Webmin logon box.

**Comment by jcameron** [comment]
Thanks for that PR! Where does the newline character that has to be removed come from though?

**Comment by johnheenan** [comment]
I have found where the extra newline comes from. Improved PR with better fix shortly.

**Comment by johnheenan** [comment]
Three commits now in the above PR

1. The improved fix to invalid link and other issues due to unfiltered new line.
2. Fix for failure to remove 'forgot password' link from Usermin login with module uninstall.
3. Improvements to code formatting for new code that did not show in original editor.

**Comment by jcameron** [comment]
Thanks for the fix! I will merge it now ...
